version: '3'

services:
  eoapi-remote-server:
    # build: 从当前路径构建镜像
    build: .
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - 3000:3000
    networks:
      - eoapi_net
    # 当前服务启动之前先要把depends_on指定的服务启动起来才行
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: eoapi-mysql
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci #设置utf8字符集
    environment:
      TZ: Asia/Shanghai
      MYSQL_DATABASE: eoapi
      MYSQL_PASSWORD: 123456a.
      MYSQL_ROOT_PASSWORD: 123456a.
    volumes:
      - ./sample/mysql/:/var/lib/mysql/ # ./sample/mysql/路径可以替换成自己的路径
    networks:
      - eoapi_net

networks:
  eoapi_net:
    name: eoapi_net
